dist: xenial

env:
  - HUGO_VERSION=0.54.0

before_install:
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o bin/hugo.tar.gz
  - tar xzvvf bin/hugo.tar.gz -C ./bin

script:
  - cd website
  - ../bin/hugo

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAJRDRD3JKBWNU5HJA
  secret_access_key:
    secure: kcpBGpcBtX3/yEqV8KLqp0EpqfWoYS9qsxMiD4zA25f0szMT8rFNafEBjd5N9LCIRitUqjaNgjtMZgRAMwgAFSlb3dqIcZ6zpFxtynAFUHlOvBxO/7N7Y/0zXaim+cKY3NoO3UYk7olRkWqX5sdydGxR93Hl/wWazvt8gAZuptTqTOPNPXzq1dSzTfXONvbAsPgkQKSVj7N4SmKMrIhMhKN4dlWsUTzTjt45WhxofMUjFm9tdLGwehvH0HVtTHmWcIGDShTI4fKFaA+GZD6M/h3H4S0u2LnBfT1+Gn65QM4lUKKTOu+2vcAvi3VX0TTTOu+4/hNMZ8jcPyyFWa3XtFyGJ1VOV6pUEB+SD9TOG24lVe7V+Aw7rE+QQgYEAYfSeByxcA7/0KA5YCFhtUlvpRtgQBCnLsRMjxf2YVfvwvBwRncxo4TPHwhje+IgL0KQgjYEoJQwlII6InbRryjLTgTx2mUV91OBYqwujZx295OtBKlUoTg0e6flFogcOgre03w6zNWmkVE1cpaFf/lOIMM19VnJ8ufMEJUgnDhdj7i62pkai/+931opI+xYMLDU++y4TuR8ca/gkfqJOKk1q1MgtE0A1potuViJ+hsR6XpET1zoJ1Z2YR+6sE9FZ5TEJVOtwfir+O0/yTNJ92dnsNQRE4Gi4HarhWnfvkjkAIY=
  bucket: "www.philiplaine.com"
  region: eu-west-1
  local-dir: public
  acl: private
  on:
    repo: phillebaba/philiplaine.com
