## Basic Configuration
baseurl = "https://www.philiplaine.com/"
languageCode = "en"
title = "P.Laine"
theme = "hyde-hyde"

## Site Settings
[params]
    author = "Philip Laine"
    description = "random thoughts and ideas about infrastructure and code"
    authorimage = "/images/philip.png"
    dateformat = "Jan 2, 2006"

    copyright = "Philip Laine"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "phillebaba"
    linkedin = "philip-laine-7a649882"
    stackoverflow = "1322872"
    email = "philip.laine@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
