## Basic Configuration
baseurl = "https://www.philiplaine.com/"
languageCode = "en"
title = "P.Laine"
theme = "hyde-hyde"

disqusShortname = "phillebaba"

## Site Settings
[params]
    author = "Philip Laine"
    title = "Title"
    description = "random thoughts and ideas about infrastructure and software"
    authorimage = "/img/philip.png"
    dateformat = "Jan 2, 2006"

    copyright = "Philip Laine"
    showBuiltWith = true

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "phillebaba"
    linkedin = "philip-laine-7a649882"
    stackoverflow = "phillebaba"
    email = "philip.laine@gmail.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
#[[menu.main]]
#    name = "Portfolio"
#    identifier = "portfolio"
#    weight = 200
#    url = "/portfolio/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
