name: verify

on: push
#on:
#  pull_request:
#    branches:
#    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.75.1"
          extended: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.3

      - name: Build Hugo
        run: make build

      - name: Lint Terraform
        run: make terraform-lint

      - name: Plan Terraform
        run: make terraform-plan
